import { useTranslation } from "react-i18next";

export const useCampaignScoreListTranslated = () => {
  const { t } = useTranslation("scores");

  return [
    {
      rank: 1,
      player: t("players.campaignPlayer1"),
      land: t("lands.campaignLand1"),
      days: 75,
      points: 200,
      creature: "",
    },
    {
      rank: 2,
      player: t("players.campaignPlayer2"),
      land: t("lands.campaignLand2"),
      days: 100,
      points: 190,
      creature: "",
    },
    {
      rank: 3,
      player: t("players.campaignPlayer3"),
      land: t("lands.campaignLand3"),
      days: 125,
      points: 180,
      creature: "",
    },
    {
      rank: 4,
      player: t("players.campaignPlayer4"),
      land: t("lands.campaignLand4"),
      days: 150,
      points: 170,
      creature: "",
    },
    {
      rank: 5,
      player: t("players.campaignPlayer5"),
      land: t("lands.campaignLand5"),
      days: 175,
      points: 160,
      creature: "",
    },
    {
      rank: 6,
      player: t("players.campaignPlayer6"),
      land: t("lands.campaignLand6"),
      days: 200,
      points: 150,
      creature: "",
    },
    {
      rank: 7,
      player: t("players.campaignPlayer7"),
      land: t("lands.campaignLand7"),
      days: 250,
      points: 140,
      creature: "",
    },
    {
      rank: 8,
      player: t("players.campaignPlayer8"),
      land: t("lands.campaignLand8"),
      days: 500,
      points: 130,
      creature: "",
    },
    {
      rank: 9,
      player: t("players.campaignPlayer9"),
      land: t("lands.campaignLand9"),
      days: 750,
      points: 120,
      creature: "",
    },
    {
      rank: 10,
      player: t("players.campaignPlayer10"),
      land: t("lands.campaignLand10"),
      days: 1000,
      points: 100,
      creature: "",
    },
    {
      rank: 11,
      player: t("players.campaignPlayer11"),
      land: t("lands.campaignLand11"),
      days: 2000,
      points: 1,
      creature: "",
    },
  ];
};

export const useStandardScoreListTranslated = () => {
  const { t } = useTranslation("scores");

  return [
    {
      rank: 1,
      player: t("players.standardPlayer1"),
      land: t("lands.standardLand1"),
      days: 75,
      points: 200,
      creature: "",
    },
    {
      rank: 2,
      player: t("players.standardPlayer2"),
      land: t("lands.standardLand2"),
      days: 100,
      points: 190,
      creature: "",
    },
    {
      rank: 3,
      player: t("players.standardPlayer3"),
      land: t("lands.standardLand3"),
      days: 125,
      points: 180,
      creature: "",
    },
    {
      rank: 4,
      player: t("players.standardPlayer4"),
      land: t("lands.standardLand4"),
      days: 150,
      points: 170,
      creature: "",
    },
    {
      rank: 5,
      player: t("players.standardPlayer5"),
      land: t("lands.standardLand5"),
      days: 175,
      points: 160,
      creature: "",
    },
    {
      rank: 6,
      player: t("players.standardPlayer6"),
      land: t("lands.standardLand6"),
      days: 200,
      points: 150,
      creature: "",
    },
    {
      rank: 7,
      player: t("players.standardPlayer7"),
      land: t("lands.standardLand7"),
      days: 250,
      points: 140,
      creature: "",
    },
    {
      rank: 8,
      player: t("players.standardPlayer8"),
      land: t("lands.standardLand8"),
      days: 500,
      points: 130,
      creature: "",
    },
    {
      rank: 9,
      player: t("players.standardPlayer9"),
      land: t("lands.standardLand9"),
      days: 750,
      points: 120,
      creature: "",
    },
    {
      rank: 10,
      player: t("players.standardPlayer10"),
      land: t("lands.standardLand10"),
      days: 1000,
      points: 100,
      creature: "",
    },
    {
      rank: 11,
      player: t("players.standardPlayer11"),
      land: t("lands.standardLand11"),
      days: 2000,
      points: 1,
      creature: "",
    },
  ];
};
